version: '3'

services:

  udp-server:
      container_name: udp-server
      build:
        context: ./udp_server

  dns-api:
      privileged: true
      build:
        context: ./api
      ports:
        - 443:443
