version: '3.7'

services:

  dns-interceptor:
      container_name: dns-interceptor
      build:
        context: ./dns_interceptor
      networks:
        dns_network:
          ipv4_address: "10.5.0.7"

  dns-api:
      container_name: dns-api
      privileged: true
      build:
        context: ./api
      networks:
        dns_network:
          ipv4_address: "10.5.0.6"
      ports:
        - 443:443

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./elasticsearch
    environment:
      - discovery.type=single-node
    networks:
        dns_network:
          ipv4_address: "10.5.0.5"
    ports:
      - 9200:9200
      
  kibana:
    container_name: kibana
    build:
      context: ./kibana
    environment:
        - ELASTICSEARCH_HOSTS=http://10.5.0.5:9200
    networks:
        dns_network:
          ipv4_address: "10.5.0.4"
    ports:
      - 5601:5601

networks:
    dns_network:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
