version: '3.7'

services:

  udp-server:
      container_name: udp-server
      build:
        context: ./udp_server
      networks:
        dns_network:
          ipv4_address: "10.5.0.7"

  dns-api:
      container_name: dns-api
      privileged: true
      build:
        context: ./api
      networks:
        dns_network:
          ipv4_address: "10.5.0.6"
      ports:
        - 443:443

#   elasticsearch:
#     container_name: elasticsearch
#     build:
#       context: ./elasticsearch
#     restart: always
#     environment:
#       node.name: "es01"
#       cluster.name: es-docker-cluster
#       cluster.initial_master_nodes: "es01"
#       bootstrap.memory_lock: "true"
#       ES_JAVA_OPTS: "-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - ./data01:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       elasticsearch_network:
#         aliases:
#           - elasticsearch_host

# volumes:
#   data01: {}


networks:
    dns_network:
      driver: bridge
      ipam:
        config:
          - subnet: 10.5.0.0/16
  # elasticsearch_network:
  #   name: elasticsearch_net
  #   driver: bridge